version: '3.8'

services:
  backend:
    build:
      context: ./backend # Path to your backend Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend # Path to your frontend Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
